# Generated by Django 4.2.4 on 2023-08-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('reading_id', models.IntegerField(primary_key=True, serialize=False)),
                ('BPNumber', models.IntegerField()),
                ('fullname', models.CharField(max_length=50)),
                ('accNumber', models.IntegerField()),
                ('meterReading', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
