# Generated by Django 4.2.4 on 2023-10-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='reading_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
